//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csce361project1145.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commentId { get; set; }
        public int pictureId { get; set; }
        public int userId { get; set; }
        public string commentText { get; set; }
    
        public virtual user user { get; set; }
        public virtual picture picture { get; set; }
    }
}
