//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csce361project1145.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public picture()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int pictureId { get; set; }
        public string url { get; set; }
        public int userId { get; set; }
        public string caption { get; set; }
        public int locationId { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual location location { get; set; }
        public virtual user user { get; set; }
    }
}
